sudo: false
language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python$TRAVIS_PYTHON_VERSION/site-packages
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/bin

before_install:
  - DIR=$(pwd)
  - cd ..
  - curl -L -O http://sourceforge.net/projects/pyqt/files/sip/sip-4.14.1/sip-4.14.1.tar.gz
  - tar -xvf sip-4.14.1.tar.gz
  - cd sip-4.14.1
  - python configure.py -e ${VIRTUAL_ENV}/include
  - make -j 2
  - make install
  - cd ..
  - curl -L -O http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.9.5/PyQt-x11-gpl-4.9.5.tar.gz
  - tar -xvf PyQt-x11-gpl-4.9.5.tar.gz
  - cd PyQt-x11-gpl-4.9.5
  - python configure.py --confirm-license
  - make -j 2
  - make install
  - cd $DIR
install:
  - env
  - ls -al $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - ls -al $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/bin
  - pip install -r requirements/test.txt
  - pip install coveralls
  - ls -al $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - ls -al $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/bin

# command to run tests
script: nosetests

after_script:
  - coveralls


