# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'i10.ui'
#
# Created: Tue Jul  5 14:25:59 2016
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_i10_knobs(object):
    def setupUi(self, i10_knobs):
        i10_knobs.setObjectName(_fromUtf8("i10_knobs"))
        i10_knobs.resize(892, 528)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(i10_knobs.sizePolicy().hasHeightForWidth())
        i10_knobs.setSizePolicy(sizePolicy)
        i10_knobs.setMinimumSize(QtCore.QSize(0, 0))
        i10_knobs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        i10_knobs.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(i10_knobs)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.status_gridlayout = QtGui.QGridLayout()
        self.status_gridlayout.setObjectName(_fromUtf8("status_gridlayout"))
        self.magnet_led = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnet_led.sizePolicy().hasHeightForWidth())
        self.magnet_led.setSizePolicy(sizePolicy)
        self.magnet_led.setMinimumSize(QtCore.QSize(30, 30))
        self.magnet_led.setMaximumSize(QtCore.QSize(30, 30))
        self.magnet_led.setAutoFillBackground(True)
        self.magnet_led.setFrameShape(QtGui.QFrame.WinPanel)
        self.magnet_led.setFrameShadow(QtGui.QFrame.Sunken)
        self.magnet_led.setLineWidth(1)
        self.magnet_led.setMidLineWidth(0)
        self.magnet_led.setObjectName(_fromUtf8("magnet_led"))
        self.status_gridlayout.addWidget(self.magnet_led, 0, 5, 1, 1)
        self.burt_label = QtGui.QLabel(self.centralwidget)
        self.burt_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.burt_label.setObjectName(_fromUtf8("burt_label"))
        self.status_gridlayout.addWidget(self.burt_label, 0, 7, 1, 1)
        self.burt_led = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.burt_led.sizePolicy().hasHeightForWidth())
        self.burt_led.setSizePolicy(sizePolicy)
        self.burt_led.setMinimumSize(QtCore.QSize(30, 30))
        self.burt_led.setMaximumSize(QtCore.QSize(30, 30))
        self.burt_led.setAutoFillBackground(True)
        self.burt_led.setFrameShape(QtGui.QFrame.WinPanel)
        self.burt_led.setFrameShadow(QtGui.QFrame.Sunken)
        self.burt_led.setLineWidth(1)
        self.burt_led.setMidLineWidth(0)
        self.burt_led.setObjectName(_fromUtf8("burt_led"))
        self.status_gridlayout.addWidget(self.burt_led, 0, 8, 1, 1)
        self.cycling_label = QtGui.QLabel(self.centralwidget)
        self.cycling_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cycling_label.setObjectName(_fromUtf8("cycling_label"))
        self.status_gridlayout.addWidget(self.cycling_label, 0, 0, 1, 1)
        self.magnet_label = QtGui.QLabel(self.centralwidget)
        self.magnet_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.magnet_label.setObjectName(_fromUtf8("magnet_label"))
        self.status_gridlayout.addWidget(self.magnet_label, 0, 3, 1, 1)
        self.cycling_textbox = QtGui.QTextEdit(self.centralwidget)
        self.cycling_textbox.setMinimumSize(QtCore.QSize(80, 28))
        self.cycling_textbox.setMaximumSize(QtCore.QSize(120, 28))
        self.cycling_textbox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cycling_textbox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.cycling_textbox.setAcceptDrops(False)
        self.cycling_textbox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cycling_textbox.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cycling_textbox.setReadOnly(True)
        self.cycling_textbox.setObjectName(_fromUtf8("cycling_textbox"))
        self.status_gridlayout.addWidget(self.cycling_textbox, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.status_gridlayout.addItem(spacerItem, 0, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.status_gridlayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.status_gridlayout)
        self.graph_layout = QtGui.QGridLayout()
        self.graph_layout.setObjectName(_fromUtf8("graph_layout"))
        self.verticalLayout.addLayout(self.graph_layout)
        self.table_widget = QtGui.QTableWidget(self.centralwidget)
        self.table_widget.setMinimumSize(QtCore.QSize(0, 160))
        self.table_widget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_widget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_widget.setAutoScroll(False)
        self.table_widget.setTabKeyNavigation(False)
        self.table_widget.setProperty("showDropIndicator", False)
        self.table_widget.setDragDropOverwriteMode(False)
        self.table_widget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.table_widget.setCornerButtonEnabled(False)
        self.table_widget.setRowCount(5)
        self.table_widget.setColumnCount(7)
        self.table_widget.setObjectName(_fromUtf8("table_widget"))
        item = QtGui.QTableWidgetItem()
        self.table_widget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_widget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_widget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_widget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_widget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table_widget.setItem(0, 0, item)
        self.verticalLayout.addWidget(self.table_widget)
        self.button_gridlayout = QtGui.QGridLayout()
        self.button_gridlayout.setSpacing(4)
        self.button_gridlayout.setObjectName(_fromUtf8("button_gridlayout"))
        self.hbpm1_plus_button = QtGui.QPushButton(self.centralwidget)
        self.hbpm1_plus_button.setObjectName(_fromUtf8("hbpm1_plus_button"))
        self.button_gridlayout.addWidget(self.hbpm1_plus_button, 0, 0, 1, 1)
        self.hbpm2_plus_button = QtGui.QPushButton(self.centralwidget)
        self.hbpm2_plus_button.setObjectName(_fromUtf8("hbpm2_plus_button"))
        self.button_gridlayout.addWidget(self.hbpm2_plus_button, 0, 1, 1, 1)
        self.scale_plus_button = QtGui.QPushButton(self.centralwidget)
        self.scale_plus_button.setEnabled(False)
        self.scale_plus_button.setObjectName(_fromUtf8("scale_plus_button"))
        self.button_gridlayout.addWidget(self.scale_plus_button, 0, 2, 1, 1)
        self.k3_plus_button = QtGui.QPushButton(self.centralwidget)
        self.k3_plus_button.setEnabled(False)
        self.k3_plus_button.setObjectName(_fromUtf8("k3_plus_button"))
        self.button_gridlayout.addWidget(self.k3_plus_button, 0, 3, 1, 1)
        self.bump_left_plus_button = QtGui.QPushButton(self.centralwidget)
        self.bump_left_plus_button.setObjectName(_fromUtf8("bump_left_plus_button"))
        self.button_gridlayout.addWidget(self.bump_left_plus_button, 0, 4, 1, 1)
        self.bump_right_plus_button = QtGui.QPushButton(self.centralwidget)
        self.bump_right_plus_button.setMinimumSize(QtCore.QSize(0, 0))
        self.bump_right_plus_button.setObjectName(_fromUtf8("bump_right_plus_button"))
        self.button_gridlayout.addWidget(self.bump_right_plus_button, 0, 5, 1, 1)
        self.vbpm1_plus_button = QtGui.QPushButton(self.centralwidget)
        self.vbpm1_plus_button.setEnabled(False)
        self.vbpm1_plus_button.setObjectName(_fromUtf8("vbpm1_plus_button"))
        self.button_gridlayout.addWidget(self.vbpm1_plus_button, 0, 6, 1, 1)
        self.vbpm2_plus_button = QtGui.QPushButton(self.centralwidget)
        self.vbpm2_plus_button.setEnabled(False)
        self.vbpm2_plus_button.setObjectName(_fromUtf8("vbpm2_plus_button"))
        self.button_gridlayout.addWidget(self.vbpm2_plus_button, 0, 7, 1, 1)
        self.hbpm1_minus_button = QtGui.QPushButton(self.centralwidget)
        self.hbpm1_minus_button.setObjectName(_fromUtf8("hbpm1_minus_button"))
        self.button_gridlayout.addWidget(self.hbpm1_minus_button, 1, 0, 1, 1)
        self.hbpm2_minus_button = QtGui.QPushButton(self.centralwidget)
        self.hbpm2_minus_button.setObjectName(_fromUtf8("hbpm2_minus_button"))
        self.button_gridlayout.addWidget(self.hbpm2_minus_button, 1, 1, 1, 1)
        self.scale_minus_button = QtGui.QPushButton(self.centralwidget)
        self.scale_minus_button.setEnabled(False)
        self.scale_minus_button.setObjectName(_fromUtf8("scale_minus_button"))
        self.button_gridlayout.addWidget(self.scale_minus_button, 1, 2, 1, 1)
        self.k3_minus_button = QtGui.QPushButton(self.centralwidget)
        self.k3_minus_button.setEnabled(False)
        self.k3_minus_button.setObjectName(_fromUtf8("k3_minus_button"))
        self.button_gridlayout.addWidget(self.k3_minus_button, 1, 3, 1, 1)
        self.bump_left_minus_button = QtGui.QPushButton(self.centralwidget)
        self.bump_left_minus_button.setObjectName(_fromUtf8("bump_left_minus_button"))
        self.button_gridlayout.addWidget(self.bump_left_minus_button, 1, 4, 1, 1)
        self.bump_right_minus_button = QtGui.QPushButton(self.centralwidget)
        self.bump_right_minus_button.setObjectName(_fromUtf8("bump_right_minus_button"))
        self.button_gridlayout.addWidget(self.bump_right_minus_button, 1, 5, 1, 1)
        self.vbpm1_minus_button = QtGui.QPushButton(self.centralwidget)
        self.vbpm1_minus_button.setEnabled(False)
        self.vbpm1_minus_button.setObjectName(_fromUtf8("vbpm1_minus_button"))
        self.button_gridlayout.addWidget(self.vbpm1_minus_button, 1, 6, 1, 1)
        self.vbpm2_minus_button = QtGui.QPushButton(self.centralwidget)
        self.vbpm2_minus_button.setEnabled(False)
        self.vbpm2_minus_button.setObjectName(_fromUtf8("vbpm2_minus_button"))
        self.button_gridlayout.addWidget(self.vbpm2_minus_button, 1, 7, 1, 1)
        self.verticalLayout.addLayout(self.button_gridlayout)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.small_correction_radiobutton = QtGui.QRadioButton(self.centralwidget)
        self.small_correction_radiobutton.setObjectName(_fromUtf8("small_correction_radiobutton"))
        self.gridLayout.addWidget(self.small_correction_radiobutton, 0, 3, 1, 1)
        self.full_correcton_radiobutton = QtGui.QRadioButton(self.centralwidget)
        self.full_correcton_radiobutton.setChecked(True)
        self.full_correcton_radiobutton.setObjectName(_fromUtf8("full_correcton_radiobutton"))
        self.gridLayout.addWidget(self.full_correcton_radiobutton, 0, 2, 1, 1)
        self.reenable_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.reenable_checkbox.setEnabled(True)
        self.reenable_checkbox.setObjectName(_fromUtf8("reenable_checkbox"))
        self.gridLayout.addWidget(self.reenable_checkbox, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        i10_knobs.setCentralWidget(self.centralwidget)

        self.retranslateUi(i10_knobs)
        QtCore.QMetaObject.connectSlotsByName(i10_knobs)

    def retranslateUi(self, i10_knobs):
        i10_knobs.setWindowTitle(QtGui.QApplication.translate("i10_knobs", "I10 Knobs", None, QtGui.QApplication.UnicodeUTF8))
        self.burt_label.setText(QtGui.QApplication.translate("i10_knobs", "BURT Status", None, QtGui.QApplication.UnicodeUTF8))
        self.cycling_label.setText(QtGui.QApplication.translate("i10_knobs", "Cycling Status", None, QtGui.QApplication.UnicodeUTF8))
        self.magnet_label.setText(QtGui.QApplication.translate("i10_knobs", "Magnet Status", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_widget.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("i10_knobs", "FCHIC-01", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_widget.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("i10_knobs", "FCHIC-02", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_widget.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("i10_knobs", "FCHIC-03", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_widget.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("i10_knobs", "FCHIC-04", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_widget.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("i10_knobs", "FCHIC-05", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_widget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("i10_knobs", "High\n"
"Limit", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_widget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("i10_knobs", "High", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_widget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("i10_knobs", "Target\n"
"Offset", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_widget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("i10_knobs", "Actual\n"
"Offset", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_widget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("i10_knobs", "Low", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_widget.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("i10_knobs", "Low\n"
"Limit", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_widget.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("i10_knobs", "Errors", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.table_widget.isSortingEnabled()
        self.table_widget.setSortingEnabled(False)
        self.table_widget.setSortingEnabled(__sortingEnabled)
        self.hbpm1_plus_button.setText(QtGui.QApplication.translate("i10_knobs", "H BPM1 +", None, QtGui.QApplication.UnicodeUTF8))
        self.hbpm2_plus_button.setText(QtGui.QApplication.translate("i10_knobs", "H BPM2 +", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_plus_button.setText(QtGui.QApplication.translate("i10_knobs", "SCALE +", None, QtGui.QApplication.UnicodeUTF8))
        self.k3_plus_button.setText(QtGui.QApplication.translate("i10_knobs", "K3 +", None, QtGui.QApplication.UnicodeUTF8))
        self.bump_left_plus_button.setText(QtGui.QApplication.translate("i10_knobs", "BUMP LEFT +", None, QtGui.QApplication.UnicodeUTF8))
        self.bump_right_plus_button.setText(QtGui.QApplication.translate("i10_knobs", "BUMP RIGHT +", None, QtGui.QApplication.UnicodeUTF8))
        self.vbpm1_plus_button.setText(QtGui.QApplication.translate("i10_knobs", "V BPM1 +", None, QtGui.QApplication.UnicodeUTF8))
        self.vbpm2_plus_button.setText(QtGui.QApplication.translate("i10_knobs", "V BPM2 +", None, QtGui.QApplication.UnicodeUTF8))
        self.hbpm1_minus_button.setText(QtGui.QApplication.translate("i10_knobs", "H BPM1 -", None, QtGui.QApplication.UnicodeUTF8))
        self.hbpm2_minus_button.setText(QtGui.QApplication.translate("i10_knobs", "H BPM2 -", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_minus_button.setText(QtGui.QApplication.translate("i10_knobs", "SCALE -", None, QtGui.QApplication.UnicodeUTF8))
        self.k3_minus_button.setText(QtGui.QApplication.translate("i10_knobs", "K3 -", None, QtGui.QApplication.UnicodeUTF8))
        self.bump_left_minus_button.setText(QtGui.QApplication.translate("i10_knobs", "BUMP LEFT -", None, QtGui.QApplication.UnicodeUTF8))
        self.bump_right_minus_button.setText(QtGui.QApplication.translate("i10_knobs", "BUMP RIGHT -", None, QtGui.QApplication.UnicodeUTF8))
        self.vbpm1_minus_button.setText(QtGui.QApplication.translate("i10_knobs", "V BPM1 -", None, QtGui.QApplication.UnicodeUTF8))
        self.vbpm2_minus_button.setText(QtGui.QApplication.translate("i10_knobs", "V BPM2 +", None, QtGui.QApplication.UnicodeUTF8))
        self.small_correction_radiobutton.setText(QtGui.QApplication.translate("i10_knobs", "0.1x Correction", None, QtGui.QApplication.UnicodeUTF8))
        self.full_correcton_radiobutton.setText(QtGui.QApplication.translate("i10_knobs", "Full Correction", None, QtGui.QApplication.UnicodeUTF8))
        self.reenable_checkbox.setText(QtGui.QApplication.translate("i10_knobs", "Re-enable forbidden buttons", None, QtGui.QApplication.UnicodeUTF8))

